application:
    defaultNamespace: AA\Controller
    namespaces:
        AA\Controller: ../Controller
        AA\Library: ../Library
        AA\Service: ../Services
    router:
        adapter: Annotations
        default:
            controller: index
            action: index
        notFound:
            controller: notFound
            action: index
        routes:
            resource: ../config/routes.yml
httpClient:
    options:
        return_transfer: 1
        return_headers: 1